// <auto-generated />
using System;
using Dziennik_szkolny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dziennik_szkolny.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dziennik_szkolny.Models.Klasa", b =>
                {
                    b.Property<int>("Id_klasy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_klasy"));

                    b.Property<string>("NazwaKlasy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_klasy");

                    b.ToTable("Klasy");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Nauczyciel", b =>
                {
                    b.Property<int>("Id_wychowawcy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_wychowawcy"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_wychowawcy");

                    b.ToTable("Nauczyciele");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Ocena", b =>
                {
                    b.Property<int>("Id_oceny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_oceny"));

                    b.Property<DateTime>("DataWpisu")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Ucznia")
                        .HasColumnType("int");

                    b.Property<int>("Id_nauczyciela")
                        .HasColumnType("int");

                    b.Property<int>("Id_przedmiotu")
                        .HasColumnType("int");

                    b.Property<int>("Wartosc")
                        .HasColumnType("int");

                    b.HasKey("Id_oceny");

                    b.HasIndex("Id_Ucznia");

                    b.HasIndex("Id_nauczyciela");

                    b.HasIndex("Id_przedmiotu");

                    b.ToTable("Oceny");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Przedmiot", b =>
                {
                    b.Property<int>("Id_przedmiotu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_przedmiotu"));

                    b.Property<int>("Id_nauczyciela")
                        .HasColumnType("int");

                    b.Property<string>("NazwaPrzedmiotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_przedmiotu");

                    b.HasIndex("Id_nauczyciela");

                    b.ToTable("Przedmioty");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Rodzic", b =>
                {
                    b.Property<int>("Id_rodzica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_rodzica"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_rodzica");

                    b.ToTable("Rodzice");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Uczen", b =>
                {
                    b.Property<int>("Id_Ucznia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ucznia"));

                    b.Property<int>("Id_klasy")
                        .HasColumnType("int");

                    b.Property<int>("Id_rodzica")
                        .HasColumnType("int");

                    b.Property<int>("Id_wychowawcy")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Ucznia");

                    b.HasIndex("Id_klasy");

                    b.HasIndex("Id_rodzica");

                    b.HasIndex("Id_wychowawcy");

                    b.ToTable("Uczniowie");
                });

            modelBuilder.Entity("KlasaPrzedmiot", b =>
                {
                    b.Property<int>("KlasyId_klasy")
                        .HasColumnType("int");

                    b.Property<int>("PrzedmiotyId_przedmiotu")
                        .HasColumnType("int");

                    b.HasKey("KlasyId_klasy", "PrzedmiotyId_przedmiotu");

                    b.HasIndex("PrzedmiotyId_przedmiotu");

                    b.ToTable("KlasaPrzedmiot", (string)null);
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Ocena", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Uczen", "Uczen")
                        .WithMany("Oceny")
                        .HasForeignKey("Id_Ucznia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Nauczyciel", "Nauczyciel")
                        .WithMany()
                        .HasForeignKey("Id_nauczyciela")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Przedmiot", "Przedmiot")
                        .WithMany("Oceny")
                        .HasForeignKey("Id_przedmiotu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nauczyciel");

                    b.Navigation("Przedmiot");

                    b.Navigation("Uczen");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Przedmiot", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Nauczyciel", "Nauczyciel")
                        .WithMany("ProwadzonePrzedmioty")
                        .HasForeignKey("Id_nauczyciela")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Nauczyciel");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Uczen", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Klasa", "Klasa")
                        .WithMany("Uczniowie")
                        .HasForeignKey("Id_klasy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Rodzic", "Rodzic")
                        .WithMany("Uczniowie")
                        .HasForeignKey("Id_rodzica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Nauczyciel", "Wychowawca")
                        .WithMany("Wychowankowie")
                        .HasForeignKey("Id_wychowawcy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klasa");

                    b.Navigation("Rodzic");

                    b.Navigation("Wychowawca");
                });

            modelBuilder.Entity("KlasaPrzedmiot", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Klasa", null)
                        .WithMany()
                        .HasForeignKey("KlasyId_klasy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Przedmiot", null)
                        .WithMany()
                        .HasForeignKey("PrzedmiotyId_przedmiotu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Klasa", b =>
                {
                    b.Navigation("Uczniowie");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Nauczyciel", b =>
                {
                    b.Navigation("ProwadzonePrzedmioty");

                    b.Navigation("Wychowankowie");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Przedmiot", b =>
                {
                    b.Navigation("Oceny");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Rodzic", b =>
                {
                    b.Navigation("Uczniowie");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Uczen", b =>
                {
                    b.Navigation("Oceny");
                });
#pragma warning restore 612, 618
        }
    }
}
