// <auto-generated />
using System;
using Dziennik_szkolny.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dziennik_szkolny.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Dziennik_szkolny.Models.Klasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaKlasy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WychowawcaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WychowawcaId");

                    b.ToTable("Klasy");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Konto");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Nauczyciel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyWychowawca")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KontoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrzelozonyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KontoId");

                    b.HasIndex("PrzelozonyId");

                    b.ToTable("Nauczyciele");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Ocena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrzedmiotId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UczenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wartosc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrzedmiotId");

                    b.HasIndex("UczenId");

                    b.ToTable("Oceny");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Ogloszenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ogloszenie");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Przedmiot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Przedmioty");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Rodzic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KontoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UczenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KontoId");

                    b.HasIndex("UczenId");

                    b.ToTable("Rodzice");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Uczen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KlasaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KontoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KlasaId");

                    b.HasIndex("KontoId");

                    b.ToTable("Uczniowie");
                });

            modelBuilder.Entity("KlasaPrzedmiot", b =>
                {
                    b.Property<int>("KlasyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrzedmiotyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("KlasyId", "PrzedmiotyId");

                    b.HasIndex("PrzedmiotyId");

                    b.ToTable("KlasaPrzedmiot", (string)null);
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Klasa", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Nauczyciel", "Wychowawca")
                        .WithMany()
                        .HasForeignKey("WychowawcaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Wychowawca");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Nauczyciel", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Konto", "Konto")
                        .WithMany()
                        .HasForeignKey("KontoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Nauczyciel", "Przelozony")
                        .WithMany()
                        .HasForeignKey("PrzelozonyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Konto");

                    b.Navigation("Przelozony");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Ocena", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Przedmiot", "Przedmiot")
                        .WithMany()
                        .HasForeignKey("PrzedmiotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Uczen", "Uczen")
                        .WithMany("Oceny")
                        .HasForeignKey("UczenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Przedmiot");

                    b.Navigation("Uczen");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Rodzic", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Konto", "Konto")
                        .WithMany()
                        .HasForeignKey("KontoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Uczen", "Uczen")
                        .WithMany()
                        .HasForeignKey("UczenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Konto");

                    b.Navigation("Uczen");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Uczen", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Klasa", "Klasa")
                        .WithMany("Uczniowie")
                        .HasForeignKey("KlasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Konto", "Konto")
                        .WithMany()
                        .HasForeignKey("KontoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klasa");

                    b.Navigation("Konto");
                });

            modelBuilder.Entity("KlasaPrzedmiot", b =>
                {
                    b.HasOne("Dziennik_szkolny.Models.Klasa", null)
                        .WithMany()
                        .HasForeignKey("KlasyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dziennik_szkolny.Models.Przedmiot", null)
                        .WithMany()
                        .HasForeignKey("PrzedmiotyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Klasa", b =>
                {
                    b.Navigation("Uczniowie");
                });

            modelBuilder.Entity("Dziennik_szkolny.Models.Uczen", b =>
                {
                    b.Navigation("Oceny");
                });
#pragma warning restore 612, 618
        }
    }
}
